### PR TITLE
Restructuring of code into modules

### PR DESCRIPTION
**Pull request by zayenz**
This is quite a large PR, and the point of opening it is to ask if the changes are of interest for you.

In order to use the code in a personal project I restructured the code into several modules. One benefit is that the longest file (expressions.rs) at just over 700 lines. All the types and methods used by fzn2lp are re-exported from the top-level so that it compiles without any changes.

This PR represents a work in progress state, and names of modules and the number of modules is not fixed nor intended to be final. 

Some additional changes are updating to nom 7.0.0-alpha2 (no changes needed to the code), separating out dev-dependencies, and some minor fixes. Parsing strings with escaped characters is also added, fixing issue #4.

As said, this PR is intended to see if the changes might be of interest to you as well.

All formatting done by cargo fmt.

### CODE REVIEW

**Comment by sthiele** [comment]
Thank you. I've not checked the PR in detail, but judging from your description I think I would be happy to accept your PR.

**Comment by zayenz** [comment]
Cool. Then I will take a second run through what I've done and make sure I think it looks reasonable after thinking about it more. Main thing is to recheck that all elements are in reasonably named modules and that the module division feels natural.

**Comment by zayenz** [comment]
I've done a second pass through, and I did some additional changes to the structure. I'm feeling happy with the current structure.

Instead of nesting almost everything inside the statements-module, the sub-modules were brought up to the top-level. In addition, for parameters, predicates, and variables their corresponding _declarations and _types module were moved to be in modules {parameters,predicates,variables}/{declarations,types}.rs instead. This gives a nice symmetry to the three parts in my view.

Please don't hesitate to ask for any desired additional changes or modifications to make this suitable addition.

**Comment by zayenz** [comment]
Updated locally, could reproduce compilation fail, and pushed the changes.

**Comment by zayenz** [comment]
Pushed update now that nom 7.0.0 is released.

**Comment by sthiele** [comment]
Thanks. I reorganized the includes here 5f6dab75966e32e90ad4e19c8d084e4b7ab3e85a.

**Comment by sthiele** [comment]
All changes are included in https://github.com/potassco/flatzinc/pull/20
Closing this. Thank you.

**Pull request closed without merging**
