### PR TITLE
Add `TryFrom<Expr> for _` and `From<_> for Expr`; where `_` are the 8 subsets of the `Expr` variants

### PR DESCRIPTION
**Pull request by Apanatshka**
I didn't see a CONTRIBUTING file, and this was quick enough to write, so I decided to go straight to a PR instead of opening an issue first. Hope you don't mind.

### CODE REVIEW

**Comment by sthiele** [comment]
Thanks for the PR. And thank you for the heads-up regarding the Contributing file. I added it [here](https://github.com/potassco/flatzinc/blob/master/CONTRIBUTING.md). 
If you agree that your contribution is licensed under the MIT I would merge your PR.

**Comment by Apanatshka** [comment]
Oops, sorry for the slow response. Yes, I agree that my contribution will be licensed and distributed under the MIT license.

**Comment by sthiele** [comment]
No problem. 
BTW, do you need a new release with these changes?

**Comment by sthiele** [comment]
I rebased your changes [pr33-rebased](https://github.com/potassco/flatzinc/tree/pr33-rebased) on my latest WIP branch where I rewrote the parser with a new library.
I would prefer to use this branch for the next release ... so maybe want to test it to make sure it works for you.

**Comment by sthiele** [comment]
The latest version v0.3.20 contains your changes and has been uploaded to crates.io

**Pull request closed without merging**
